In [1]:
import os
import tensorflow as tf
from tensorflow import keras

In [12]:
x = tf.constant([1, 2, 3.3])
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [22]:
a = tf.constant("Hello, Deep Learning")
tf.strings.lower(a)
a = tf.constant(True)
a == True

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [50]:
tf.constant(35000,dtype=tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-30536>

In [54]:
b = tf.cast(a, tf.float32)

In [55]:
print(a)
print(b)

tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(1.0, shape=(), dtype=float32)


In [57]:
a = tf.constant([-1, 0, 1, 2])
aa = tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

In [63]:
tf.convert_to_tensor([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [74]:
a = tf.ones([3,4,2])
a

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [75]:
tf.zeros_like(a)

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [85]:
tf.fill([],-1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [87]:
tf.random.normal([3,4,5],mean=3,stddev=0.1)

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[2.8030725, 2.9235516, 3.1956594, 2.9660256, 2.8453882],
        [3.0520995, 3.0092082, 2.9721081, 3.0301104, 3.2774704],
        [2.882402 , 3.1917517, 3.0449169, 3.0410814, 3.2441483],
        [2.9899118, 2.9519002, 3.1460824, 3.0957508, 3.0549932]],

       [[2.9822025, 2.9204667, 3.2370248, 2.9437485, 2.9079993],
        [2.9972992, 2.9662077, 2.917755 , 2.9814436, 3.0909324],
        [2.9694195, 3.0326602, 2.8827229, 3.104799 , 3.006134 ],
        [2.9535472, 2.8875458, 2.9027948, 2.90231  , 2.8400772]],

       [[2.9415958, 2.8361337, 2.9512744, 2.9567823, 2.937967 ],
        [2.9890895, 3.1773634, 3.162536 , 3.1451173, 2.9656756],
        [3.1606   , 2.960913 , 3.0290024, 2.9641316, 2.9885678],
        [2.9898896, 3.1044762, 2.8364933, 2.9731994, 3.13095  ]]],
      dtype=float32)>

In [89]:
tf.random.uniform([3,4,5])

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0.6633643 , 0.67797935, 0.69027114, 0.87368715, 0.6643665 ],
        [0.98936546, 0.3828994 , 0.2782812 , 0.07435739, 0.34756923],
        [0.1310234 , 0.16619349, 0.02000904, 0.5422838 , 0.5551357 ],
        [0.00239873, 0.03630102, 0.8523805 , 0.29979634, 0.24886632]],

       [[0.34663892, 0.87023807, 0.586311  , 0.31509745, 0.7102649 ],
        [0.11899543, 0.65783477, 0.61003304, 0.9174305 , 0.22956002],
        [0.9053352 , 0.7995442 , 0.26565433, 0.10967302, 0.16720414],
        [0.13719785, 0.07970631, 0.8885206 , 0.733915  , 0.30916965]],

       [[0.04556072, 0.02295792, 0.02865803, 0.8022412 , 0.3285221 ],
        [0.23471391, 0.31596196, 0.4048586 , 0.8546896 , 0.49191248],
        [0.09020543, 0.31312883, 0.19099009, 0.24308014, 0.40023768],
        [0.7262976 , 0.60219383, 0.7620299 , 0.26478565, 0.04990184]]],
      dtype=float32)>

In [92]:
tf.random.uniform([3,4,5],maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[32, 65, 41, 78, 77],
        [33, 37, 50, 27, 47],
        [61, 47, 93, 42, 87],
        [25, 37, 75, 77,  7]],

       [[21, 93, 38, 44, 22],
        [70, 91,  3, 67,  8],
        [ 7, 54, 38, 16, 71],
        [91,  8,  0, 63, 46]],

       [[82, 74, 43, 14, 36],
        [26, 55, 59, 30,  5],
        [35, 44, 54, 66, 89],
        [70, 36, 60, 50,  2]]], dtype=int32)>

In [97]:
tf.range(3,10,2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 5, 7, 9], dtype=int32)>

In [105]:
out = tf.random.uniform([4, 10])
y = tf.constant([2,3,2,0])
y = tf.one_hot(y,depth=10)
loss = tf.keras.losses.mse(y, out)
loss = tf.reduce_mean(loss)
print(loss)

tf.Tensor(0.3480971, shape=(), dtype=float32)


In [113]:
z = tf.random.normal([4, 2])
b = tf.zeros([2])
z = z + b
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 1.2792069 ,  0.7454619 ],
       [ 1.0367222 , -0.7480224 ],
       [-0.3583646 ,  1.3586928 ],
       [-0.45293355,  1.6054922 ]], dtype=float32)>

In [114]:
fc = layers.Dense(3)
fc.build(input_shape=(2,4))
fc.bias

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [118]:
x = tf.random.normal([2, 4])
w = tf.ones([4, 3])
b = tf.zeros([3])
o = x@w + b
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.48724264, -0.48724264, -0.48724264],
       [-2.5090156 , -2.5090156 , -2.5090156 ]], dtype=float32)>

In [120]:
fc = layers.Dense(3)
fc.build(input_shape=(2,4))
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.8899883 , -0.52495253, -0.64758635],
       [ 0.46887314, -0.21476102,  0.21977055],
       [ 0.5451962 , -0.6822146 , -0.28289062],
       [ 0.5429745 , -0.49046877,  0.5321493 ]], dtype=float32)>

In [123]:
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words=10000)

In [135]:
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)
embedding = layers.Embedding(10000, 100)
out = embedding(x_train)
x_train.shape, out.shape

((25000, 80), TensorShape([25000, 80, 100]))

In [137]:
x = tf.random.normal([4, 32, 32, 3])
layer = layers.Conv2D(16, kernel_size=3)
out = layer(x)
out.shape

TensorShape([4, 30, 30, 16])

In [145]:
x = tf.random.normal([4, 32, 32, 3])
print(x[2][1][0][1])
# print(x[0,::])
print(x[:,0:28:2,0:28:2,:])

tf.Tensor(0.24849918, shape=(), dtype=float32)
tf.Tensor(
[[[[-1.2094318  -0.9028578   1.6594533 ]
   [-0.26581135 -0.6810744   0.2871027 ]
   [ 0.6668348  -0.9246452   0.75215274]
   ...
   [ 0.7229144  -0.46289924 -1.1159753 ]
   [ 0.80000156  0.06371789 -0.12601377]
   [-1.5107578  -0.85401434  0.27971518]]

  [[-0.27350566  2.3344498  -0.564572  ]
   [ 0.12324466 -1.9025409  -0.4386757 ]
   [ 0.5046681  -0.6584325   0.76949716]
   ...
   [-0.68126416 -0.8863308   1.693977  ]
   [ 1.3994899   0.28959447  0.8723373 ]
   [ 0.56338125  0.9446914  -0.20153347]]

  [[-1.315197    0.10308175  1.0458436 ]
   [ 0.3819917  -2.5189185   0.13597086]
   [ 0.45312476 -0.06352972 -0.7170906 ]
   ...
   [-2.4397588   1.0086209  -0.31772938]
   [ 0.9138182  -2.367727   -0.8364552 ]
   [-2.2545774   0.88370526 -0.67705166]]

  ...

  [[-2.4832702   1.2969681  -1.7727062 ]
   [-0.4992465   1.318758   -0.06087336]
   [-0.45691037  0.8437855   0.06611647]
   ...
   [ 0.28355473 -0.10706925  0.6737946 ]

In [149]:
x = tf.range(96)
x = tf.reshape(x,[2,4,4,3])
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [151]:
x.ndim,x.shape

(4, TensorShape([2, 4, 4, 3]))

In [153]:
tf.reshape(x, [2,-1])

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [177]:
x = tf.random.uniform([28,28], maxval=10, dtype=tf.int32)
x.ndim, x.shape

(2, TensorShape([28, 28]))

In [178]:
x = tf.expand_dims(x, axis=2)
x.ndim, x.shape

(3, TensorShape([28, 28, 1]))

In [179]:
x = tf.expand_dims(x, axis=0)
x.ndim, x.shape

(4, TensorShape([1, 28, 28, 1]))

In [180]:
x = tf.squeeze(x ,axis=0)
x.ndim, x.shape

(3, TensorShape([28, 28, 1]))

In [182]:
x = tf.random.normal([2, 32, 32, 3])
x = tf.transpose(x, perm=[0,3,1,2])
x.ndim, x.shape

(4, TensorShape([2, 3, 32, 32]))

In [183]:
x = tf.transpose(x, perm=[0,2,1,3])
x.ndim, x.shape

(4, TensorShape([2, 32, 3, 32]))

In [200]:
b = tf.constant([1, 2])
print(b.shape)
b = tf.expand_dims(b, axis=0)
print(b.shape)
print(b)

(2,)
(1, 2)
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)


In [201]:
b = tf.tile(b, multiples=[2,1])
print(b)

tf.Tensor(
[[1 2]
 [1 2]], shape=(2, 2), dtype=int32)


In [206]:
x = tf.range(4)
x = tf.reshape(x, [2,2])
x = tf.tile(x, multiples=[1,2])
x

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]], dtype=int32)>

In [207]:
x = tf.tile(x, multiples=[2,1])
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]], dtype=int32)>

In [210]:
A = tf.random.normal([32,1])
tf.broadcast_to(A, [2, 32, 32, 3])

<tf.Tensor: shape=(2, 32, 32, 3), dtype=float32, numpy=
array([[[[-0.350776  , -0.350776  , -0.350776  ],
         [-0.77328306, -0.77328306, -0.77328306],
         [-1.8248601 , -1.8248601 , -1.8248601 ],
         ...,
         [-1.2168727 , -1.2168727 , -1.2168727 ],
         [-0.99852   , -0.99852   , -0.99852   ],
         [ 0.654797  ,  0.654797  ,  0.654797  ]],

        [[-0.350776  , -0.350776  , -0.350776  ],
         [-0.77328306, -0.77328306, -0.77328306],
         [-1.8248601 , -1.8248601 , -1.8248601 ],
         ...,
         [-1.2168727 , -1.2168727 , -1.2168727 ],
         [-0.99852   , -0.99852   , -0.99852   ],
         [ 0.654797  ,  0.654797  ,  0.654797  ]],

        [[-0.350776  , -0.350776  , -0.350776  ],
         [-0.77328306, -0.77328306, -0.77328306],
         [-1.8248601 , -1.8248601 , -1.8248601 ],
         ...,
         [-1.2168727 , -1.2168727 , -1.2168727 ],
         [-0.99852   , -0.99852   , -0.99852   ],
         [ 0.654797  ,  0.654797  ,  0.654797  ]

In [212]:
a = tf.range(5)
b = tf.constant(2)
print(a // b)
print(a % b)

tf.Tensor([0 0 1 1 2], shape=(5,), dtype=int32)
tf.Tensor([0 1 0 1 0], shape=(5,), dtype=int32)


In [216]:
x = tf.range(4)
tf.pow(x, 3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27], dtype=int32)>

In [217]:
tf.pow(3, x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  3,  9, 27], dtype=int32)>

In [218]:
a = tf.random.normal([4, 3, 28, 32])
b = tf.random.normal([4, 3, 32, 2])
(a@b).shape

TensorShape([4, 3, 28, 2])

In [220]:
a = tf.random.normal([4, 28, 32])
b = tf.random.normal([32, 16])
tf.matmul(a, b)

<tf.Tensor: shape=(4, 28, 16), dtype=float32, numpy=
array([[[ 1.1769979e+00,  2.6845994e+00,  3.3244271e+00, ...,
          1.0807622e+01,  3.5855303e+00, -4.0663395e+00],
        [-7.1452360e+00,  8.9746237e+00,  3.3259363e+00, ...,
          1.9240060e+00, -9.6263132e+00,  1.2559872e+00],
        [ 2.8608503e+00,  2.4810357e+00, -1.4778905e+00, ...,
         -2.2827835e+00,  9.0525160e+00, -5.8842950e+00],
        ...,
        [-5.2156606e+00, -3.2343068e+00, -8.1636596e-01, ...,
         -2.0449471e+00,  5.1299829e+00, -7.2864227e+00],
        [ 7.9065032e+00,  3.5925512e+00,  3.7203938e-01, ...,
         -5.7447205e+00,  7.9752793e+00, -7.1722627e+00],
        [ 5.8058391e+00, -2.7147498e+00, -2.9787629e+00, ...,
          1.0145667e+00,  5.1340904e+00, -4.9066329e+00]],

       [[-8.6282701e+00,  1.6662896e-01,  8.8635845e+00, ...,
          7.5261397e+00, -1.1978743e+01, -2.3463945e+00],
        [ 6.6135377e-01,  1.6545407e+00,  9.8228674e+00, ...,
          7.0836039e+00, -1.20

In [2]:
w1 = tf.Variable(tf.random.truncated_normal([784,256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
w2 = tf.Variable(tf.random.truncated_normal([256,128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))
w3 = tf.Variable(tf.random.truncated_normal([128,10], stddev=0.1))
b3 = tf.Variable(tf.zeros([10]))

In [4]:
from tensorflow.keras import datasets
with tf.GradientTape() as tape:
    (x, y), (x_val, y_val) = datasets.mnist.load_data()
    x = tf.reshape(tf.cast(x, tf.float32), [-1, 28*28])
    h1 = x@w1 + tf.broadcast_to(b1, [x.shape[0], 256])
    h1 = tf.nn.relu(h1)
    h2 = h1@w2 + b2
    h2 = tf.nn.relu(h2)
    out = h2@w3 + b3
    y_onehot = tf.one_hot(y, depth=10)
    loss = tf.square(y_onehot - out)
    loss = tf.reduce_mean(loss)

In [5]:
loss

<tf.Tensor: shape=(), dtype=float32, numpy=37752.39>

In [236]:
x.shape

TensorShape([60000, 784])